POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "user1",
    "password": "1234"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "user5",
    "password": "qwerty"
}

###

GET http://localhost:3000/requests/apps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjUyNzg5NSwiZXhwIjoxNzg2NTI4Nzk1fQ.YxOPwM0ECeVcqSIlrdW9a5BYFnJB1YkV764b0cw6s4M


###

GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjUyNTU0NSwiZXhwIjoxNzg2NTI2NDQ1fQ.-nKn8orINr3YxPMvkJNDzAGg4u7qhNwuh4IZpdafZvw


###
GET http://localhost:3000/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjUyODg4OCwiZXhwIjoxNzg2NTI5Nzg4fQ.ghgMzW3ne76WA2YetGW5AfQ6V9FJlZ9NwCBIJ_0p8TQ

###
POST http://localhost:3000/requests/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2MjhjNWU3LTU0M2ItNGM5MC1iMzIwLTRkZjA0ZTgxMThhMCIsImlhdCI6MTc4NjU1OTU0NSwiZXhwIjoxNzg2NTYwNDQ1fQ.dqMjB6wBX5IMtOidNIMtj7hTpxaDQM7eMQQ6RIesOpk
Content-Type: application/json

{
    "appId": "494b86c5-f6ef-4afc-9616-4cc19a5c43bc",
    "level": "READ",
    "reason": "hello world"
}

###

POST http://localhost:3000/ai/requests/7bfda555-fd94-4ff5-8443-89956dfe8954/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjU1MDA4MiwiZXhwIjoxNzg2NTUwOTgyfQ.DUe4Fxk0TuAsGIK2B9_VxUV93GEkmE9qnmtqn8IWWQw


