POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "user1",
    "password": "1234"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "user5",
    "password": "qwerty"
}

###

GET http://localhost:3000/requests/apps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjUyNzg5NSwiZXhwIjoxNzg2NTI4Nzk1fQ.YxOPwM0ECeVcqSIlrdW9a5BYFnJB1YkV764b0cw6s4M


###

GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjUyNTU0NSwiZXhwIjoxNzg2NTI2NDQ1fQ.-nKn8orINr3YxPMvkJNDzAGg4u7qhNwuh4IZpdafZvw


###
GET http://localhost:3000/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjUyODg4OCwiZXhwIjoxNzg2NTI5Nzg4fQ.ghgMzW3ne76WA2YetGW5AfQ6V9FJlZ9NwCBIJ_0p8TQ

###
POST http://localhost:3000/requests/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhiMTQxYTgwLTY5ODEtNGQzZC04MjQwLTMyOWU1ZTJjZmNlYiIsImlhdCI6MTc4NjU1OTcyMCwiZXhwIjoxNzg2NTYwNjIwfQ.bORE2AN7mGzc0ef38BbOm4HFdXHwm6A6MAexBlm9GUc
Content-Type: application/json

{
    "appId": "494b86c5-f6ef-4afc-9616-4cc19a5c43bc",
    "level": "READ",
    "reason": "hello world"
}

###

POST http://localhost:3000/ai/requests/be1a93bd-62ba-4843-9e38-b9ddd47381b9/review
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjA2MjhjNWU3LTU0M2ItNGM5MC1iMzIwLTRkZjA0ZTgxMThhMCIsImlhdCI6MTc4NjU3MTYyNywiZXhwIjoxNzg2NTcyNTI3fQ.D4zcyGu8Hi-WhLphPSmRlKIkfpW0uX2arriklTAklxQ


